Fungus
TheSlayerMC/Journey-1.12 pull request #61
Opened 2021-01-15 18:53 UTC by DiamondWalker

JourneyEffectCloudEntity doesn't save all info to NBT properly; apparently I'm too dumb to use NBTLists.

Everything else should be working as intended.

Full changelog:
-added custom effect cloud class. Acts similar to the vanilla cloud class, but a lot more customizable (for example, you can add exceptions and give the clouds advanced life cycles with different growth and shrinking stages).

-made honglows save variants properly

-honglows inflict different effects now. These were designed to give players disadvantages against nearby mobs, but this ability might need adjusting depending on how often situations where they are useful occur

-removed uneeded hostile code from hongos and honglows (but I didn't make them extend EntityCreature as of this push)

-removed hongo and honglow poison immunity; custom effect class handles this now

-reverted super hurt call with permission from dizzle

2021-01-15 20:06 UTC, TimeConqueror requested changes

2021-01-15 20:06 UTC, TimeConqueror commented on src/main/java/net/jitl/client/render/entity/HonglowRenderer.java
> +		return JITL.rl("textures/entity/overworld/" + textures[entityIn.getVariant()]);
it's better to store full location instead of String parts, so just store here an array of ResourceLocations

2021-01-15 20:06 UTC, TimeConqueror commented on src/main/java/net/jitl/common/entity/overworld/HonglowEntity.java
> +	      this.getEntityData().set(VARIANT, this.random.nextInt(3));
Since variants are finite and their count is small, it's better to create enum with name 'Type' and RED, BLUE, GREEN values. 
Firstly it will be safe and won't crash with ArrayOutOfBoundsException. 
VARIANT data parameter now will be not Integer, but your enum - Type. 
So you need a custom encoder. To do it, register your custom DataSerializerEntry (forge registry). To see how you can encode enum to bytes, look at DataSerialers.DIRECTION.

2021-01-15 20:06 UTC, TimeConqueror commented on src/main/java/net/jitl/common/entity/overworld/HonglowEntity.java
> +		nbt.putInt("Color", this.getEntityData().get(VARIANT));
To save your Type enum, use Type.<some_instance>.ordinal()
To create your Type from nbt (integer), use Type.values(nbt.getInt("Color") % Type.values().length)

2021-01-15 20:06 UTC, TimeConqueror commented on src/main/java/net/jitl/common/entity/projectile/base/JourneyEffectCloudEntity.java
> +public class JourneyEffectCloudEntity extends Entity {
We name journey version of vanilla alternatives with J prefix, so it's better to make it JEffectCloudEntity

2021-01-15 20:06 UTC, TimeConqueror commented on src/main/java/net/jitl/common/entity/overworld/HonglowEntity.java
> +    				case 0: //blue
no more hardcode with Type enum:  you can store there the effect or even method implementation.

2021-01-15 20:06 UTC, TimeConqueror commented on src/main/java/net/jitl/common/entity/projectile/base/JourneyEffectCloudEntity.java
> +		sizes.add(new ImmutablePair<Integer, Float>(time, size));
add check that time is greater or equals 0, this can be done via adding `Requirements.greaterOrEqualsThan(time, 0);`

2021-01-15 20:06 UTC, TimeConqueror commented on src/main/java/net/jitl/common/entity/projectile/base/JourneyEffectCloudEntity.java
> +	public ArrayList<LivingEntity> exceptions = new ArrayList<LivingEntity>(); //the enemies who are exceptions
with direct reference you will create memory leak, because these entities won't be unloaded. So you need to save not entities, but their unique ids.

2021-01-15 20:06 UTC, TimeConqueror commented on src/main/java/net/jitl/common/entity/projectile/base/JourneyEffectCloudEntity.java
> +				float timeBetweenPairs = ((Integer) nextPair.getKey()).intValue() - ((Integer) previousPair.getKey()).intValue();
pls remove boxings and casts

2021-01-15 20:06 UTC, TimeConqueror commented on src/main/java/net/jitl/common/entity/projectile/base/JourneyEffectCloudEntity.java
> +		if (isOwnerException && entity == owner) return true;
btw, the owner should also be stored as UUID

2021-01-15 20:06 UTC, TimeConqueror commented on src/main/java/net/jitl/common/entity/projectile/base/JourneyEffectCloudEntity.java
> +		nbt.putUUID("Owner UUID", owner.getUUID());
may you name nbt keys in snake_case?

2021-01-15 20:06 UTC, TimeConqueror commented on src/main/java/net/jitl/common/entity/projectile/base/JourneyEffectCloudEntity.java
> +		return (LivingEntity) (LivingEntity) ((ServerWorld) this.level).getEntity(id);
.___.

2021-01-15 20:08 UTC, TimeConqueror commented on src/main/java/net/jitl/client/render/entity/HonglowRenderer.java
> +		return JITL.rl("textures/entity/overworld/" + textures[entityIn.getVariant()]);
below I wrote about Types, so it's better to store texture locations in that enum

2021-01-17 05:10 UTC, DiamondWalker commented
Closing because idk how to edit pull requests

2021-01-17 05:10 UTC, closed without merging